Repository d-coder111/DSAmplify, pull requests merged in 2023-10, with the labels that each got.

#1 Add OrderAgnosticBS.java
  JAVA/OrderAgnosticBS.java
Labels: hacktoberfest, hacktoberfest-accepted

#3 Adding goals in README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 Create Min & Max in array.java
  JAVA/Min & Max in array.java
Labels: hacktoberfest, hacktoberfest-accepted

#7 Adding Interpolation Search
  JAVA/InterpolationSearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#9 Adding to-do tasks for this repo
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#11 Adding Find Peak Element
  JAVA/FindPeakElement.java
Labels: hacktoberfest, hacktoberfest-accepted

#12 Added SumListRecursively
  JAVA/SumListRecursively.java
Labels: hacktoberfest, hacktoberfest-accepted

#13 Add ContainsDuplicate
  JAVA/ContainsDuplicate.java
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added SumListIterative
  JAVA/SumListIterative.java
Labels: hacktoberfest, hacktoberfest-accepted

#16 Add ContainsDuplicate for C++
  C++/ContainsDuplicate.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 Create LinearSearch.java
  JAVA/LinearSearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#19 Add FindPeakElement for C++
  C++/FindPeakElement.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#18 Fixed class name in FindPeakElement
  JAVA/FindPeakElement.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Create website table format showing program+contributors of this repository #8
  index.html
  script.js
  styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#22 Suduko Solver
  JAVA/sudoku_solver.java
Labels: hacktoberfest, hacktoberfest-accepted

#24 Next Greater Element Leetcode Problem
  JAVA/Next_Greater_Element.java
Labels: hacktoberfest, hacktoberfest-accepted

#25 Binary Search
  JAVA/Binary_Search.java
Labels: hacktoberfest, hacktoberfest-accepted

#26 Find The Safe Position
  JAVA/Find_the_safe_position.java
Labels: hacktoberfest, hacktoberfest-accepted

#27 Create MergeSort.java
  JAVA/MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#28 Create AddTwoNumbersInLinkedList.cpp
  C++/AddTwoNumbersInLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#29 Create MedianOf2SortedArrays.cpp
  MedianOf2SortedArrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#31 Create ReverseNodesInKGroups.cpp
  ReverseNodesInKGroups.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 Create NextPermultation.cpp
  NextPermultation.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 Merge Sort Algorithm added
  C++/merge_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#34 Insertion Sort added
  C++/insertion_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#32 mergeSortedLinkedLists added
  C++/mergeSortedLinkedLists.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added Dijkstras Algorithm
  C++/Dijkstras.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Add AI_Algorithms_with_java
  JAVA/BFS_Traversal.java
  JAVA/Contraint.java
  JAVA/Greedy_search.java
  JAVA/Tic_Tac_Toe_AI.java
  JAVA/Tic_Tac_Toe_normal.java
Labels: hacktoberfest, hacktoberfest-accepted

#39 Binary Search Treee Added
  C++/BST.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#41 Heap Sort Added
  C++/heapSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 Prims Algorithm added
  C++/Prims.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#40 nth root of a given number
  JAVA/nthRootOfaNumber.java
Labels: hacktoberfest, hacktoberfest-accepted

#48 Binary Search Added
  C++/binary_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#49 Create ReverseNodesInKGroups.cpp
  C++/ReverseNodesInKGroups.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 Knapsack Problem Added
  C++/KnapsackProblem.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 Create NextPermultation.cpp
  C++/NextPermultation.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 Create MedianOf2SortedArrays.cpp
  C++/MedianOf2SortedArrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#52 Create InsertionSort
  JAVA/InsertionSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#53 add counting sort in java
  JAVA/CountingSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#54 add Given a Perfect Binary Tree, reverse the alternate level nodes of…
  JAVA/PerfectBinaryTree.java
Labels: hacktoberfest, hacktoberfest-accepted

#55 Add Euler Totient Function with java
  JAVA/EulerTotientFunction.java
Labels: hacktoberfest, hacktoberfest-accepted

#56 Add Zeros of Polynomial with java
  JAVA/PolynomialRoots.java
Labels: hacktoberfest, hacktoberfest-accepted

#57 Kadane's Algorithm
  JAVA/Kadane's_Algorithm.java
Labels: hacktoberfest, hacktoberfest-accepted

#59 Added Calculator using Java
  JAVA/Calculator.java
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create DFS_TRAVERSAL.java
  JAVA/DFS_TRAVERSAL.java
Labels: hacktoberfest, hacktoberfest-accepted

#62 Create SieveOfEratosthenes.cpp
  C++/SieveOfEratosthenes.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#61 Create SieveOfEratosthenes.java
  JAVA/SieveOfEratosthenes.java
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added SpiralMatrix.java
  JAVA/spiralMatrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#64 Bubble Sort in C++
  C++/bubbleSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 Largest_Rectangle
  C++/Largest_Rectangle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#68 Adding sortVowels.cpp
  C++/sortVowels.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 Added LCS Code
  JAVA/Longest_Common_Subsequence.java
Labels: hacktoberfest, hacktoberfest-accepted

#72 Add QuickSort Implementation
  JAVA/QuickSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#75 Create pyramid.cpp
  C++/pyramid.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#78 created a js file and added the information functionality,modify css
  index.html
  script2.js
  styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create UniqueFloydAlgorithmpo.java
  JAVA/UniqueFloydAlgorithmpo.java
Labels: hacktoberfest, hacktoberfest-accepted

#80 Add CyclicSort.java
  JAVA/CyclicSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#81 Create Moores.java
  JAVA/Moores.java
Labels: hacktoberfest, hacktoberfest-accepted

#82 Adding AllPathsInMaze.java
  JAVA/AllPathsInMaze.java
Labels: hacktoberfest, hacktoberfest-accepted

#79 Armstrong numbers in a given range program added
  JAVA/Armstrong_Numbers_InLimit.java
Labels: hacktoberfest, hacktoberfest-accepted

#84 added First_Missing_Positive program
  JAVA/First_Missing_Positive.java
Labels: hacktoberfest, hacktoberfest-accepted

#88 Added Cycle Detection in Singly Linked List Program
  JAVA/CycleDetectionSinglyLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#89 Added Length Finding of Cycle in Linked List JAVA Program
  JAVA/CycleDetectionSinglyLinkedList.java
  JAVA/CycleLengthFindingLinkedList.java
  JAVA/CycleStartNodeSearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#94 added-greedySearch Cpp
  C++/greedySearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Create find duplicates.java
  JAVA/find duplicates.java
Labels: hacktoberfest, hacktoberfest-accepted

#95 added-prims-java
  JAVA/Prims.java
Labels: hacktoberfest, hacktoberfest-accepted

#86 added Rat in Maze problem
  C++/RatInMaze.cpp
  C++/TotalOccurence.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#97 Added Linked List Cycle Length Finding in JAVA
  JAVA/CycleLengthFindingLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#101 Added FindInMountainArray question
  JAVA/Find_In_MountainArray.java
Labels: hacktoberfest, hacktoberfest-accepted

#98 Cycle Start Node finding algorithm added in JAVA
  JAVA/CycleStartNodeSearch.java
  JAVA/GCD_and_LCM.java
Labels: hacktoberfest, hacktoberfest-accepted

#102 Added Reverse Linked List in JAVA
  JAVA/ReverseLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#103 ADDED CYCLE LENGTH FINDING CODE IN JAVA
  JAVA/CycleLengthFindingLinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#100 Implemented Topological Sort in Java
  JAVA/TopologicalSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#74 Python password generator
  Python/Password Generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#83 Added the code for bubble sorting technique using java
  JAVA/BubbleSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#96 Created floyd.cpp
  C++/floyd.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#85 Priority Queue
  C++/Priority Queue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#109 Added Search_In_Rotated_Sorted_Array question
  JAVA/Search_In_Rotated_Sorted_Array.class
  JAVA/Search_In_Rotated_Sorted_Array.java
  JAVA/Solution.class
Labels: hacktoberfest, hacktoberfest-accepted

#110 python-binary-search.py
  Python/python-binary-search.py
Labels: hacktoberfest, hacktoberfest-accepted

#111 add python_factorial_recursion.py
  Python/python_factorial_using_recursion.py
Labels: hacktoberfest, hacktoberfest-accepted

#112 Added Valid Parentheses
  C++/ValidParentheses.cpp
  C++/ValidParentheses.exe
Labels: hacktoberfest, hacktoberfest-accepted

#114 Added LCA
  C++/LowestCommonAncestor.cpp
Labels: hacktoberfest-accepted

#115 Added MCM algorithm in C++
  C++/mcm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#116 Added segregateEvenOddLinkedList
  C++/segregateEvenOddLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#119 Added Rotation of 2d Matrix Using JAVA
  JAVA/Rotate_2D_Matrix.java
Labels: hacktoberfest, hacktoberfest-accepted

#121 Added JAVA code for Next greater element in LINKED LIST
  JAVA/Next_Greater_Linked_List.java
Labels: hacktoberfest, hacktoberfest-accepted

#120 Checking Number is Palindrome or Not using recursive method in Java
  JAVA/Palindrome.java
Labels: hacktoberfest, hacktoberfest-accepted

#122 Number of digit in a number in java
  JAVA/Number_of_digits_in_a_number.java
Labels: hacktoberfest, hacktoberfest-accepted

#123 Checking Valid Anagram
  JAVA/Anagram.java
Labels: hacktoberfest, hacktoberfest-accepted

#124 Added next greater element to left in JAVA
  JAVA/next_greater_left.java
Labels: hacktoberfest, hacktoberfest-accepted

#126 ADDED next smaller element in array in JAVA
  JAVA/next_smaller_right_array.java
Labels: hacktoberfest, hacktoberfest-accepted

#128 Lexiographically Greater String in Java
  JAVA/lexiographically_larger_String.java
Labels: hacktoberfest, hacktoberfest-accepted

#127 Added JAVA code for finding next smaller element Using Stack
  JAVA/next_smaller_left_array.java
Labels: hacktoberfest, hacktoberfest-accepted

#129 Added a JAVA code for next greater element in array
  JAVA/next_greater_right_element_array.java
Labels: hacktoberfest, hacktoberfest-accepted

#130 Prime no checking in java
  JAVA/primeno.java
Labels: hacktoberfest, hacktoberfest-accepted

#131 Pyramid star pattern in java
  JAVA/Pyramid_pattern.java
Labels: hacktoberfest, hacktoberfest-accepted

#113 Create TowerOfHanoi
  JAVA/TowerOfHanoi.java
Labels: hacktoberfest, hacktoberfest-accepted

#132 Binary Search Using Recursion in Java
  JAVA/Binary_Search_Recursion.java
Labels: hacktoberfest, hacktoberfest-accepted

#133 Python program to: sum-array-element-using-recursion.py
  Python/sum-array-element-using-recursion.py
Labels: hacktoberfest, hacktoberfest-accepted
