Repository d-coder111/DSAmplify, pull requests merged in 2024-10, with the labels that each got.

#139 added ReverseWords.java
  JAVA/ReverseWords.java
Labels: hacktoberfest, hacktoberfest-accepted

#142 added my contribution ~
  Python/alarm_clock.py
Labels: hacktoberfest

#144 Add about page
  about.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#146 added MergeSort.py
  Python/MergeSort.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#145 Added a better about page
  about.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#147 added BubbleSort.py
  Python/BubbleSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#149 Create guessNumberGame.java
  JAVA/guessNumberGame.java
Labels: hacktoberfest, hacktoberfest-accepted

#148 Added the NQueen problem for the issue #136
  JAVA/NQueen.java
Labels: hacktoberfest, hacktoberfest-accepted

#150 added my contribution
  Python/digital book/digital_book.py
  Python/digital book/working screenshot.png
Labels: hacktoberfest, hacktoberfest-accepted

#151 problem 641 leetcode design circular deque
  C++/641_Design_Circular_Deque.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#152 BST (Binary Search Tree) Implementation
  Python/BSTimplementation.py
Labels: hacktoberfest, hacktoberfest-accepted

#157 Add app.py
  app.py
  templates/about.html
  templates/index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#160 Add duplicate checker script to detect duplicate files.
  check_duplicates.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#161 Configure GitHub Actions to run duplicate checker.
  .github/workflows/duplicate-check.yml
  templates/index.html
Labels: hacktoberfest, hacktoberfest-accepted
